config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  devise_for :customers, controllers: {
    sessions: "customers_devise/sessions",
    passwords: "customers_devise/passwords",
    registrations: "customers_devise/registrations"
  }
  devise_scope :customers do
    match '/customers/sign_out', to: 'customers_devise/session#destroy', via: Devise.mappings[:customer].sign_out_via
  end

  devise_for :admins, controllers: {
    sessions: "admin/devise/sessions",
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations"
  }

  # admin
  namespace :admin do
    root 'homes#top'
    get 'homes/top'
    resources :orders, except: [:new, :create, :destroy]
    resources :order_products, except: [:new, :create, :edit, :show, :destroy, :index]
    resources :customers, except: [:new, :create, :destroy]
    resources :products, except: :destroy
    resources :genres, except: [:new, :show, :destroy]
  end

  # customer
  get 'homes/top'
  get 'homes/about'

  resource :customer, only: [:edit, :update, :show] do
    member do
      get 'withdraw_confirm'
      patch 'withdraw'
    end
  end

  resources :orders, except: [:edit, :destroy] do
    collection do
      get 'thanks'
      post 'confirm'
    end
  end

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, except: [:new, :edit, :show]
  resources :products, only: [:index, :show] do
    get 'search', on: :collection
  end
  resources :deliveries, except: [:new, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :deliveries, dependent: :destroy

  enum admittion_status: { withdraw: false, validity: true}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_KATAKANA = /\A[\p{katakana}\p{blank}ー－]+\z/
  VALID_ZIP_CODE = /\A\d{3}[-]\d{4}\z/  # 郵便番号（ハイフンあり7桁）
  VALID_TEL = /\A\d{3}[-]\d{3}[-]\d{4}|\d{3}[-]\d{4}[-]\d{4}\z/  # 電話番号
  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :kana_last_name,  format: {
                                  with: VALID_KATAKANA,
                                  message: 'はカタカナで入力してください。'
                                }
    validates :kana_first_name, format: {
                                  with: VALID_KATAKANA,
                                  message: 'はカタカナで入力してください。'
                                }
    validates :zip_code,        format: {
                                  with: VALID_ZIP_CODE,
                                  message: "はハイフンあり7桁で入力してください。"
                                }
    validates :address
    validates :tel,             format: {
                                  with: VALID_TEL,
                                  message: "の入力が間違っています（ハイフンありの数字）"
                                }
    validates :email,           format: {
                                  with: VALID_EMAIL_REGEX
                                }
  end

  # カートアイテム合計
  def cart_item_sum
    total = 0
    cart_items.each do |cart_item|
      total += cart_item.subtotal_price
    end
    total
  end

  def status_validity?
    admittion_status == "validity"
  end

  # カート商品合計個数
  def cart_total_count
    count = 0
    cart_items.each do |cart_item|
      count += cart_item.count
    end
    count
  end

  # ログイン時に退会済会員はログインできないようにする
  def active_for_authentication?
    super && status_validity?
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::BaseController
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id), notice: '会員情報を更新しました。'
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :zip_code, :address, :tel, :email, :admittion_status)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def edit
    @customer = Customer.find(current_customer.id)
  end

  def update
  end

  def show
    @customer = Customer.find(current_customer.id)
  end

  def withdraw_confirm
  end

  def withdraw
    @customer = Customer.find(current_customer.id)
    if @customer.update!(admittion_status: "withdraw")
      
      redirect_to customers_sign_out_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="maypage-main">
      <p id="notice"><%= notice %></p>
      <h2 class="mypage-title">マイページ</h2>
      <div class="mypage-flex-group mypage-register-info-header">
        <span>登録情報</span>
        <%= link_to '編集する',edit_customer_registration_path, class: "btn btn-success" %>
        <%= link_to 'パスワードを変更する', new_customer_password_path(@customer), class: "btn btn-success" %>
      </div>
      <table class="row table table-bordered mypage-register-info-table">
        <tr>
          <th class="col-xs-3 active">氏名</th>
          <td class="col-xs-9"><%= @customer.last_name + "　" + @customer.first_name %></td>
        </tr>
        <tr>
          <th class="active">カナ</th>
          <td><%= @customer.kana_last_name + "　" + @customer.kana_first_name %></td>
        </tr>
        <tr>
          <th class="active">郵便番号</th>
          <td><%= '〒' + @customer.zip_code %></td>
        </tr>
        <tr>
          <th class="active">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th class="active">電話番号</th>
          <td><%= @customer.tel %></td>
        </tr>
        <tr>
          <th class="active">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
      </table>

      <div class="mypage-flex-group">
        <span>配送先</span>
        <%= link_to '一覧を見る', deliveries_path, class: "btn btn-default" %>
      </div>
      <div class="mypage-flex-group">
        <span>注文履歴</span>
        <td><%= link_to '一覧を見る', orders_path, class: "btn btn-default" %></td>
      </div>
    </div>
  </div>
</div>

app/views/customers/withdraw_confirm.html.erb
<div class="withdraw-confirm-box">
  <p class="withdraw-confirm-title">本当に退会しますか？</p>
  <p class="withdraw-confirm-message">
    退会すると、会員登録情報や<br>
    これまでの購入履歴が閲覧できなくなります。<br>
    退会する場合は、「退会する」をクリックしてください。<br>
  </p>

  <div class="withdraw-confirm-btn-group">
    <%= link_to '退会しない', customer_path, class: "btn btn-primary" %>
    <%= link_to '退会する', withdraw_customer_path, method: :patch, class: "btn btn-danger" %>
  </div>
</div>