config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  devise_for :customers, controllers: {
    sessions: "customers_devise/sessions",
    passwords: "customers_devise/passwords",
    registrations: "customers_devise/registrations"
  }
  devise_scope :customers do
    match '/customers/sign_out', to: 'customers_devise/session#destroy', via: Devise.mappings[:customer].sign_out_via
  end

  devise_for :admins, controllers: {
    sessions: "admin/devise/sessions",
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations"
  }

  # admin
  namespace :admin do
    root 'homes#top'
    get 'homes/top'
    resources :orders, except: [:new, :create, :destroy]
    resources :order_products, except: [:new, :create, :edit, :show, :destroy, :index]
    resources :customers, except: [:new, :create, :destroy]
    resources :products, except: :destroy
    resources :genres, except: [:new, :show, :destroy]
  end

  # customer
  get 'homes/top'
  get 'homes/about'

  resource :customer, only: [:edit, :update, :show] do
    member do
      get 'withdraw_confirm'
      patch 'withdraw'
    end
  end

  resources :orders, except: [:edit, :destroy] do
    collection do
      get 'thanks'
      post 'confirm'
    end
  end

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, except: [:new, :edit, :show]
  resources :products, only: [:index, :show] do
    get 'search', on: :collection
  end
  resources :deliveries, except: [:new, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :product
	belongs_to :customer

	# 小計
	def subtotal_price
		(count * product.price * Constants::TAX).round
	end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @customer = Customer.find(current_customer.id)
  end

  def create
    @cart_item = current_customer.cart_items.new(cart_item_params)
    if @cart_item.save
      redirect_to cart_items_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update!(cart_item_params)

    @customer = Customer.find(current_customer.id)
    render :index
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    if cart_item.destroy
      flash[:notice] = "カート内の商品を削除しました。"
      redirect_to cart_items_path
    else
      render action: :index
    end
  end

  def destroy_all
    customer = Customer.find(current_customer.id)
    if customer.cart_items.destroy_all
      flash[:notice] = "カート内の商品を全て削除しました。"
      redirect_to cart_items_path
    else
      render action: :index
    end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:count,:product_id)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/create.html.erb
<h1>create</h1>

app/views/cart_items/destroy.html.erb
<h1>CartItems#destroy</h1>
<p>Find me in app/views/cart_items/destroy.html.erb</p>

app/views/cart_items/destroy_all.html.erb
<h1>CartItems#destroy_all</h1>
<p>Find me in app/views/cart_items/destroy_all.html.erb</p>

app/views/cart_items/index.html.erb
<div class="container">
	<div class="row">
		<div class="ec-cart-index-main">
			<h2 class="ec-cart-index-title">ショッピングカート</h2>
			<!-- success-massage -->
			<% if flash[:notice] %>
			  <p class="success-message"><%= flash[:notice] %></p>
			<% end %>
			<!-- / -->
			<div class="btn-box text-right">
				<%= link_to "カートを空にする", cart_items_destroy_all_path, method: :delete, class:"btn btn-danger" %>
			</div>
			<!-- カート商品一覧 -->
			<div class="cart-item-table row">
				<table class="table">
					<thead>
						<tr>
							<th class="active">商品名</th>
							<th class="active text-right">単価（税込）</th>
							<th class="active text-right">数量</th>
							<th class="active text-right">小計</th>
							<th class="active"></th>
						</tr>
					</thead>
					<tbody>
						<% @customer.cart_items.each do |cart_item| %>
						<tr>
							<td><%= cart_item.product.name %></td>
							<td class="text-right"><%= cart_item.product.price_with_tax %>円</td>
							<td class="text-right">

								<%= form_for cart_item , html: {class:"form-inline"} do |f| %>
									<div class="form-group">
										<%= f.select :count,(1..10).to_a, {}, class: "form-control" %>
										<%= f.submit "変更", class:"btn btn-primary" %>
									</div>
								<% end %>

							</td>
							<td class="text-right"><%= cart_item.subtotal_price %>円</td>
							<td class="text-right"><%= link_to "削除する", cart_item_path(cart_item.id), method: :delete, class:"btn btn-danger" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<!-- 合計金額 -->
			<div class="cart-total-table row">
				<div class="col-xs-8 return-shopping-btn-wrapper"><%= link_to "買い物を続ける", homes_top_path, class:"btn btn-default" %></div>
				<div class="col-xs-4">
					<table class="table">
						<tbody>
							<th class="active">合計金額</th>
							<td class="text-right"><%= @customer.cart_item_sum %>円</td><!-- cart_item_sumはcustomerモデルに定義あり -->
						</tbody>
					</table>
				</div>
			</div>
			<!-- ボタン群 -->
      <% if current_customer.cart_items.present? %>
		<div class="create-order-btn-wrapper col-xs-4 col-xs-offset-4">
			<%= link_to "情報入力に進む", new_order_path, class:"btn btn-primary form-control" %>
        </div>
      <% end %>
		</div>
	</div>
</div>

app/views/cart_items/update.html.erb
<h1>CartItems#update</h1>
<p>Find me in app/views/cart_items/update.html.erb</p>