config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  devise_for :customers, controllers: {
    sessions: "customers_devise/sessions",
    passwords: "customers_devise/passwords",
    registrations: "customers_devise/registrations"
  }
  devise_scope :customers do
    match '/customers/sign_out', to: 'customers_devise/session#destroy', via: Devise.mappings[:customer].sign_out_via
  end

  devise_for :admins, controllers: {
    sessions: "admin/devise/sessions",
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations"
  }

  # admin
  namespace :admin do
    root 'homes#top'
    get 'homes/top'
    resources :orders, except: [:new, :create, :destroy]
    resources :order_products, except: [:new, :create, :edit, :show, :destroy, :index]
    resources :customers, except: [:new, :create, :destroy]
    resources :products, except: :destroy
    resources :genres, except: [:new, :show, :destroy]
  end

  # customer
  get 'homes/top'
  get 'homes/about'

  resource :customer, only: [:edit, :update, :show] do
    member do
      get 'withdraw_confirm'
      patch 'withdraw'
    end
  end

  resources :orders, except: [:edit, :destroy] do
    collection do
      get 'thanks'
      post 'confirm'
    end
  end

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, except: [:new, :edit, :show]
  resources :products, only: [:index, :show] do
    get 'search', on: :collection
  end
  resources :deliveries, except: [:new, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :genre
	has_many :cart_items, dependent: :destroy
	has_many :order_products,dependent: :destroy

  attachment :image

  with_options presence: true do
    validates :image
    validates :name, length: {minimum: 1, maximum:15}
    validates :description
    validates :genre_id
    validates :price, numericality: true
  end
  validates :sales_status, inclusion: {in: [true, false]}

  #単価（税込）
  def price_with_tax
    (price * Constants::TAX).round
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    @products = Product.page(params[:page]).reverse_order
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product.id), notice:'商品を作成しました'
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product.id), notice:'商品情報を更新しました'
    else
      render 'edit'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:genre_id, :name, :image, :description, :price, :sales_status)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:genre_id].present?
      @products = Product.where(genre_id: params[:genre_id])
      .page(params[:page]).per(16).reverse_order

      @product_genre = @products.first.genre if @products.count > 0
    else
      # ジャンルが無効になっている商品は一覧に表示しない
      @products = Product
        .joins(:genre).where(genres: {active_status: "有効"})
        .page(params[:page]).per(16).reverse_order
    end
    @genres = Genre.all
  end

  def search
    # application controllerで生成した@qを利用して検索する
    @q_products = @q.result.page(params[:page]).per(16).reverse_order
    @genres = Genre.all

    render :index
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new(product_id: @product.id)
    @genres = Genre.all
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% if @product.errors.any? %>
      <h4 class="errors-message">
        項目が記入されてない箇所があります。
      </h4>
      <div id ="error_explanation" class="alert alert-danger">
        <ul>
          <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="container">
        <div class="row">
          <%= form_for [:admin, @product] do |f| %>
          <div class="col-xs-5">
            <h2>商品編集画面</h2>
            <%= f.attachment_field :image %>
            <%= attachment_image_tag @product, :image, :size => '350x300', id: "file-preview" %>
          </div>
          <div class="col-xs-5 col-xs-offset-2">
            <table class="edit-form-table">
              <tbody>
                <tr>
                  <th>商品名</th>
                  <td><%= f.text_field :name, class: "form-control" %></td>
                </tr>
                <tr>
                  <th>商品説明</th>
                  <td><%= f.text_area :description, class: "form-control" %></td>
                </tr>
                <tr>
                  <th>ジャンル</th>
                  <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
                </tr>
                <tr>
                  <th>税抜き価格</th>
                  <td><%= f.text_field :price, class: "form-control" %></td>
                </tr>
                <tr>
                  <th>販売ステータス</th>
                  <td><%= f.select :sales_status, [["販売停止中",0],["販売中",1]], include_blank: "--選択してください--" %></td>
                </tr>
              </tbody>
            </table>
            <%= f.submit '更新', class: "btn btn-success btn-new-register btn-lg" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <h2>商品一覧画面</h2>
      <div class="new-btn-wrap">
        <%= link_to "商品登録", new_admin_product_path, class: "btn btn-primary btn-new-register btn-lg"; %>
      </div>
        <table class="table">
          <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜き価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td><%= link_to product.name, admin_product_path(product.id) %></td>
              <td><%= "#{product.price}円" %></td>
              <td><%= product.genre.name %></td>
              <td><%= product.sales_status ? "販売中" : "販売停止中" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row text-center">
          <%= paginate @products, class: "paginate" %>
        </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% if @product.errors.any? %>
      <h4 class="errors-message">
        項目が記入されてない箇所があります。
      </h4>
      <div id ="error_explanation" class="alert alert-danger">
        <ul>
          <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="row">
        <%= form_for(@product, url: admin_products_path) do |f| %>
        <div class="col-xs-5">
          <h2>商品登録画面</h2>
          <div class="product-new-form">
            <%= f.attachment_field :image %>
          </div>
          <div class="product-img">
            <%= image_tag 'sample_image.jpeg', id: "file-preview", :size => '350x300' %>
          </div>
        </div>
        <div class="col-xs-5 col-xs-offset-2">
          <table class="new-form-table">
            <tbody>
              <tr>
                <th>商品名</th>
                <td><%= f.text_field :name, class: "form-control" %></td>
              </tr>
              <tr>
                <th>商品説明</th>
                <td><%= f.text_area :description, class: "form-control" %></td>
              </tr>
              <tr>
                <th>ジャンル</th>
                <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
              </tr>
              <tr>
                <th>税抜き価格</th>
                <td><%= f.text_field :price, class: "form-control" %></td>
              </tr>
              <tr>
                <th>販売ステータス</th>
                <td><%= f.select :sales_status, [["販売停止中",0],["販売中",1]], include_blank: "--選択してください--" %></td>
              </tr>
            </tbody>
          </table>
          <%= f.submit '作成', class: "btn btn-success btn-new-register btn-lg" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row product-ditail-content">
    <div class="col-xs-4">
      <p id ="notice"><%= flash[:notice] %></p>
      <h2>商品詳細画面</h2>
      <%= attachment_image_tag @product, :image, :fill, 300, 300 %>
    </div>
    <div class="col-xs-8">
      <table class="table product-ditail-table">
        <tr>
          <th>商品名</th>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @product.genre.name %></td>
        </tr>
        <tr>
          <th>税抜価格</th>
          <td><%= "#{@product.price}円" %></td>
        </tr>
        <tr>
          <th>税込価格</th>
          <td><%= "#{(@product.price * Constants::TAX).round }円" %></td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td><%= @product.sales_status ? "販売中" : "販売停止中" %></td>
        </tr>
      </table>
      <div>
        <%= link_to "編集", edit_admin_product_path(@product.id), class: "btn btn-success btn-new-register btn-lg" %>
        <%= link_to "続けて登録", new_admin_product_path, class: "btn btn-success btn-new-register btn-lg"  %>
      </div>
    </div>
  </div>
</div>
</div>