config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  devise_for :customers, controllers: {
    sessions: "customers_devise/sessions",
    passwords: "customers_devise/passwords",
    registrations: "customers_devise/registrations"
  }
  devise_scope :customers do
    match '/customers/sign_out', to: 'customers_devise/session#destroy', via: Devise.mappings[:customer].sign_out_via
  end

  devise_for :admins, controllers: {
    sessions: "admin/devise/sessions",
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations"
  }

  # admin
  namespace :admin do
    root 'homes#top'
    get 'homes/top'
    resources :orders, except: [:new, :create, :destroy]
    resources :order_products, except: [:new, :create, :edit, :show, :destroy, :index]
    resources :customers, except: [:new, :create, :destroy]
    resources :products, except: :destroy
    resources :genres, except: [:new, :show, :destroy]
  end

  # customer
  get 'homes/top'
  get 'homes/about'

  resource :customer, only: [:edit, :update, :show] do
    member do
      get 'withdraw_confirm'
      patch 'withdraw'
    end
  end

  resources :orders, except: [:edit, :destroy] do
    collection do
      get 'thanks'
      post 'confirm'
    end
  end

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, except: [:new, :edit, :show]
  resources :products, only: [:index, :show] do
    get 'search', on: :collection
  end
  resources :deliveries, except: [:new, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ながのCAKE - 管理ページ</title>
  <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Kalam&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
      <div class="container-fluid">
        <div class="admin-name">
        <!-- ログイン時に名前表示 -->
          <% if admin_signed_in? %>
            <p class="text-right"><%= current_admin.name %></p>
          <% end %>
        </div>
        <div class="logo-container">
          <i class="fas fa-cheese header-icon"></i>
          <span class="nagano">ながの</span><span class="cake">CAKE</span><span>―管理者ページ―</span>
        </div>
        <div class="menu">
          <div class="navbar-right">
            <ul class="nav navbar-nav">
              <li><%= link_to "商品一覧", admin_products_path %></li>
              <li><%= link_to "会員一覧", admin_customers_path %></li>
              <li><%= link_to "注文履歴一覧", admin_orders_path %></li>
              <li><%= link_to "ジャンル一覧", admin_genres_path %></li>
              <!-- ログイン時はheaderにログアウト表示 -->
              <%  if admin_signed_in? %>
                <li><%= link_to "ログアウト", destroy_admin_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
  </header>
  <!-- /header -->
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCake</title>
    <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kalam&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c|Noto+Sans+JP|Noto+Serif+JP|Sawarabi+Gothic&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <div class="container-fluid">
        <div class="row">
          <!-- ログイン時はカスタマーの名前を表示 -->
          <% if customer_signed_in? %>
            <div class="header-line"><p class="header-name text-right"><%= current_customer.last_name + " " + current_customer.first_name %>様</p></div>
          <% end %>
          <!-- / -->
          <div class="header-vizual">
            <%= link_to(homes_top_path, class:"ec-header-logo") do %>
              <div class="logo-container">
                <i class="fas fa-cheese header-icon"></i>
                <span class="nagano">ながの</span><span class="cake">CAKE</span>
              </div>
            <% end %>
          </div>

          <div class="header-nav flex">
              <%= link_to(homes_top_path, class:"nav-link") do %><div class="header-nav-list-item">トップ</div><% end %>
              <%= link_to(homes_about_path, class:"nav-link") do %><div class="header-nav-list-item">アバウト</div><% end %>
              <!-- ログイン時はheaderにログアウト表示,ログアウト時はサインアップ表示 -->
              <%  if customer_signed_in? %>
                <%= link_to(customer_path, class:"nav-link") do %><div class="header-nav-list-item">マイページ</div><% end %>
                <%= link_to(destroy_customer_session_path, class:"nav-link") do %><div class="header-nav-list-item">ログアウト</div><% end %>
                <%= link_to(cart_items_path, class:"nav-link") do %>
                  <div class="header-nav-list-item">
                    <i class="fas fa-shopping-cart"></i>
                    <% if current_customer.cart_total_count >= 1 %>
                    <span class="label label-danger">
                      <%= current_customer.cart_total_count %>
                    </span>
                    <% end %>
                  </div>
                <% end %>
              <% else %>
                <%= link_to(new_customer_registration_path, class:"nav-link") do %><div class="header-nav-list-item">サインアップ</div><% end %>
                <%= link_to(new_customer_session_path, class:"nav-link") do %><div class="header-nav-list-item">ログイン</div><% end %>
              <% end %>
              <!-- / -->
          </div>
        </div>
      </div>
      <!-- 検索ボックス -->
      <div class="serch-form">
        <%= search_form_for @q, url: search_products_path, class: "form-inline navbar-form navbar-right" do |f| %>
          <div class="form-group">
            <%= f.label :name_or_description_cont, 'Title', class: 'control-label sr-only' %>
            <%= f.search_field :name_or_description_cont,  autofocus: true, placeholder: "お菓子を探しましょう", class: 'form-control' %>
          </div>
          <%= f.submit class: "btn btn-warning" %>
        <% end %>
        </div>
    </header>
    <!-- /header -->

    <%= yield %>

    <!-- footer -->
    <footer>
      <div class="footer-info">
        <div class="footer-headline"><h4>インフォメーション</h4></div>
        <div class="fotter-icons">
          <span><i class="fab fa-instagram"></i></span>
          <span><i class="fab fa-twitter"></i></span>
          <span><i class="fab fa-facebook-f"></i></span>
        </div>
        <div class="footer-info-contents flex">
          <div class="footer-info-box">
            <h5>お問い合わせ</h5>
            <p>
              ながのCAKE<br>
              TEL　：000-0000-0000 <br>
              MAIL ：000@00000000.com <br>
              営業時間：午前10:00～午後18:00 <br>
              ※年末年始、祝日は定休日となります。
            </p>
          </div>
          <div class="footer-info-box">
            <h5>アクセス</h5>
            <p>
              〒000-0000
              東京都×××××××××××××
              JR長野駅東口から徒歩10分
            </p>
          </div>
          <div class="footer-info-box">
            <h5>返品・交換について</h5>
            <p>
              原則として返品・交換は受け付けておりません。 「初期不良品」「注文以外の商品」などは、商品到着より3日以内にのみ返品・交換対応いたします。ただし、次の場合は返品・交換は受付けいたしかねますので、ご了承ください。 <br>
              * 開封済みの商品<br>
              * 購入者による汚損、破損された商品<br>
              * 商品到着より４日以上経過した場合<br>
              * 事前に返品・交換のご連絡がない場合
            </p>
          </div>
          <div class="footer-info-box">
            <h5>納期について</h5>
            <p>
              通常、入金確認後7営業日以内に発送致します。商品がすべてそろい次第発送させていただきますので、組み合わせによっては商品のお届け日が遅れる場合がございます。あらかじめご了承ください。
            </p>
          </div>
          <div class="footer-info-box">
            <h5>個人情報について</h5>
            <p>
              お客様からお預かりした大切な個人情報（住所・氏名・メールアドレスなど）を、裁判所や警察機関等、公共機関からの提出要請があった場合以外、公開または第三者に譲渡することは一切ございません。
            </p>
          </div>
          <div class="footer-info-box">
            <h5>お支払い方法について</h5>
            <p>
              お支払いは以下の方法がご利用いただけます。<br>
              ・クレジットカード決済<br>
              ・銀行振り込み<br>
              <br>
              下記のカード会社がご利用いただけます。<br>
              <%= image_tag('card.png', style: "width: 200px; height: 30px;") %>
            </p>
          </div>
        </div>
      </div>
      <div class="footer-visual">
        <div class="footer-cover"></div>
      </div>
      <div class="footer-under-line">
        <p>©copyright ながのCAKE All Rights Reserved.</p>
      </div>
    </footer>
    <!-- fotter -->
  </body>
</html>